GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/info

###
DELETE http://localhost:3001/api/persons/65a0bd0e63b85dbb56e6d6b

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Jimmy Tran",
    "number": "123-345"
}

###
PUT http://localhost:3001/api/persons/1 HTTP/1.1
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "123-345"
}

