GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/info

###
DELETE http://localhost:3001/api/persons/65a0bd0e63b85dbb56e6d6b

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Jim",
    "number": "123-345"
}

###
PUT http://localhost:3001/api/persons/65a38d5439a9b488205b9e15 HTTP/1.1
content-type: application/json

{
    "name": "Art",
    "number": "123-345"
}

